#org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
#android.useAndroidX=true
## This newDsl flag was added by the Flutter template
#android.newDsl=false
## This builtInKotlin flag was added by the Flutter template
#android.builtInKotlin=false

# Turunkan dari 8G ke 3072m biar Windows gak pusing ngalokasiin memorinya
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false

# TAMBAHKAN 2 BARIS INI (Biar Kotlin gak usah bikin daemon terpisah & gak pake cache bermasalah):
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false