class LifestyleModel {
  final int lifestyleId;
  final String userId;
  final int? step;
  final int? heartrate;
  final double? sleep;
  final DateTime recordedAt;

  LifestyleModel({
    required this.lifestyleId,
    required this.userId,
    this.step,
    this.heartrate,
    this.sleep,
    required this.recordedAt,
  });

  factory LifestyleModel.fromJson(Map<String, dynamic> json) {
    return LifestyleModel(
      lifestyleId: json['lifestyle_id'],
      userId: json['user_id'],
      step: json['step'],
      heartrate: json['heartrate'],
      sleep: json['sleep'] != null ? (json['sleep'] as num).toDouble() : null,
      recordedAt: DateTime.parse(json['recorded_at']).toLocal(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'user_id': userId,
      'step': step,
      'heartrate': heartrate,
      'sleep': sleep,
      // recorded_at is generated by DB usually, or we can send it explicitly
    };
  }
}
